# Generated by Django 4.2.1 on 2023-06-08 07:23

from django.db import migrations


def insert_customers(apps, schema_editor):
    Customer = apps.get_model('customer', 'Customer')

    customers = [
        Customer(customer_id='M1-ABDI-11', address='Taman Sari, Kec. Setu', city='Bekasi', state='Jawa Barat'),
        Customer(customer_id='M1-PUMS-11', address='Gunung Sindur', city='Bogor', state='Jawa Barat'),
        Customer(customer_id='M1-STQI-11', address='Kel. Rorotan- Cilincing', city='Jakarta Utara',
                 state='DKI Jakarta'),
        Customer(customer_id='M1-SUGP-11', address='Gn. Putri Kec. Gn. Putri', city='Bekasi', state='Jawa Barat'),
        Customer(customer_id='M1-SURA-11', address='Padurenan, Mustika Jaya', city='Bekasi', state='Jawa Barat'),
    ]

    Customer.objects.bulk_create(customers)


class Migration(migrations.Migration):
    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_customers),
    ]
