# Generated by Django 4.2.1 on 2023-06-08 07:39

from django.db import migrations


def insert_data(apps, schema_editor):
    Uom = apps.get_model("product", "UnitOfMeasure")
    Sku = apps.get_model("product", "Sku")

    uom = [
        Uom(name="Ton"),
        Uom(name="Batang"),
        Uom(name="Lembar")
    ]

    skus = [
        Sku(sku_id="SIK-040040-IBB"),
        Sku(sku_id="SIK-060060-IBB"),
        Sku(sku_id="SIK-070070-IBB"),
        Sku(sku_id="SIK-080080-IBB"),
        Sku(sku_id="SIK-090090-KS"),
        Sku(sku_id="SIK-100100-IBB"),
        Sku(sku_id="PLT-BRDS0230"),
        Sku(sku_id="PLT-SPHC0155"),
        Sku(sku_id="PLT-SPHC0180"),
        Sku(sku_id="PLT-SPHC0026"),
        Sku(sku_id="PLT-SPHC0280"),
        Sku(sku_id="PIP-SCH404"),
        Sku(sku_id="PIP-SCH4060"),
        Sku(sku_id="PIP-SCH4080"),
        Sku(sku_id="PLT-SPHC0400"),
        Sku(sku_id="PLT-SPHC0500"),
        Sku(sku_id="PLT-SPHC0600"),
        Sku(sku_id="PLT-SPHC1000"),
        Sku(sku_id="PLT-SPHC1200-GG"),
        Sku(sku_id="SIK-050050-IBB"),
        Sku(sku_id="SIK-120120-IBB"),
        Sku(sku_id="WFL-300-GG"),
        Sku(sku_id="UNP-200"),
        Sku(sku_id="PLT-SPHC0120"),
        Sku(sku_id="PLT-SPHC0150"),
        Sku(sku_id="PLT-SPHC0200"),
        Sku(sku_id="UNP-120"),
        Sku(sku_id="PLT-KPL0100"),
    ]

    Uom.objects.bulk_create(uom)
    Sku.objects.bulk_create(skus)


class Migration(migrations.Migration):
    run_before = [
        ('orders', '0002_auto_20230608_1513'),
    ]

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(insert_data)
    ]
