# Generated by Django 4.2.1 on 2023-06-08 07:46

from django.db import migrations


def insert_data(apps, schema_editor):
    PriceList = apps.get_model("product", "PriceList")

    price_lists = [
        PriceList(sku_id_id="PLT-SPHC1000", supplier_id_id="S1-FIX-1", price=5596216.216, stock=1),
        PriceList(sku_id_id="PLT-SPHC0400", supplier_id_id="S1-FIX-1", price=1789729.73, stock=3),
        PriceList(sku_id_id="PLT-SPHC0500", supplier_id_id="S1-FIX-1", price=2390540.541, stock=5),
        PriceList(sku_id_id="PLT-SPHC0600", supplier_id_id="S1-FIX-1", price=3008783.784, stock=4),
        PriceList(sku_id_id="PLT-SPHC1200-GG", supplier_id_id="S1-FIX-1", price=3640765.766, stock=11),
        PriceList(sku_id_id="SIK-100100-IBB", supplier_id_id="S1-FIX-1", price=1066572.973, stock=30),
        PriceList(sku_id_id="SIK-120120-IBB", supplier_id_id="S1-FIX-1", price=1540090.09, stock=5),
        PriceList(sku_id_id="SIK-040040-IBB", supplier_id_id="S1-FIX-1", price=166129.7297, stock=51),
        PriceList(sku_id_id="SIK-050050-IBB", supplier_id_id="S1-FIX-1", price=259720.7207, stock=72),
        PriceList(sku_id_id="SIK-060060-IBB", supplier_id_id="S1-FIX-1", price=372075.6757, stock=8),
        PriceList(sku_id_id="SIK-070070-IBB", supplier_id_id="S1-FIX-1", price=506627.027, stock=8),
        PriceList(sku_id_id="PIP-SCH404", supplier_id_id="S1-HSC-1", price=1559459.459, stock=3),
        PriceList(sku_id_id="PIP-SCH4060", supplier_id_id="S1-HSC-1", price=2727027.027, stock=3),
        PriceList(sku_id_id="PIP-SCH4080", supplier_id_id="S1-HSC-1", price=4163063.063, stock=2),
        PriceList(sku_id_id="PLT-SPHC1200-GG", supplier_id_id="S1-HSC-1", price=3544144.144, stock=11),
        PriceList(sku_id_id="SIK-100100-IBB", supplier_id_id="S1-HSC-1", price=990990.991, stock=30),
        PriceList(sku_id_id="SIK-120120-IBB", supplier_id_id="S1-HSC-1", price=1447747.748, stock=30),
        PriceList(sku_id_id="SIK-040040-IBB", supplier_id_id="S1-HSC-1", price=143694, stock=51),
        PriceList(sku_id_id="SIK-060060-IBB", supplier_id_id="S1-HSC-1", price=324775, stock=112),
        PriceList(sku_id_id="SIK-070070-IBB", supplier_id_id="S1-HSC-1", price=443243, stock=24),
        PriceList(sku_id_id="SIK-080080-IBB", supplier_id_id="S1-HSC-1", price=633783.7838, stock=24),
        PriceList(sku_id_id="SIK-090090-KS", supplier_id_id="S1-HSC-1", price=804504.5045, stock=52),
        PriceList(sku_id_id="UNP-200", supplier_id_id="S1-HSC-1", price=2266667, stock=6),
        PriceList(sku_id_id="PLT-SPHC0155", supplier_id_id="S1-HSC-1", price=518919, stock=50),
        PriceList(sku_id_id="PLT-SPHC0180", supplier_id_id="S1-HSC-1", price=582702.7027, stock=50),
        PriceList(sku_id_id="UNP-120", supplier_id_id="S1-HSC-1", price=1968468.468, stock=10),
        PriceList(sku_id_id="UNP-200", supplier_id_id="S1-ISB-1", price=4387387.387, stock=6),
        PriceList(sku_id_id="PLT-BRDS0230", supplier_id_id="S1-ISB-1", price=828828.8288, stock=100),
        PriceList(sku_id_id="PLT-SPHC0120", supplier_id_id="S1-ISB-1", price=400900.9009, stock=170),
        PriceList(sku_id_id="PLT-SPHC0150", supplier_id_id="S1-KPS-1", price=504504.5045, stock=20),
        PriceList(sku_id_id="PLT-SPHC0200", supplier_id_id="S1-KPS-1", price=627027.027, stock=15),
        PriceList(sku_id_id="PLT-SPHC0026", supplier_id_id="S1-PSB-1", price=788288.2883, stock=10),
        PriceList(sku_id_id="PLT-SPHC0280", supplier_id_id="S1-PSB-1", price=855855.8559, stock=20),
        PriceList(sku_id_id="SIK-100100-IBB", supplier_id_id="S1-PSB-1", price=1576767.568, stock=30),
        PriceList(sku_id_id="SIK-120120-IBB", supplier_id_id="S1-PSB-1", price=2366674.775, stock=12),
        PriceList(sku_id_id="SIK-040040-IBB", supplier_id_id="S1-SAM-1", price=151577.4775, stock=51),
        PriceList(sku_id_id="SIK-050050-IBB", supplier_id_id="S1-SAM-1", price=475662.1622, stock=72),
        PriceList(sku_id_id="SIK-060060-IBB", supplier_id_id="S1-SSC-1", price=687067.5676, stock=112),
        PriceList(sku_id_id="SIK-070070-IBB", supplier_id_id="S1-SSC-1", price=468262.1622, stock=124),
        PriceList(sku_id_id="SIK-080080-IBB", supplier_id_id="S1-SSC-1", price=1233198.198, stock=20),
        PriceList(sku_id_id="WFL-300-GG", supplier_id_id="S1-SSC-1", price=7040000, stock=8),
        PriceList(sku_id_id="PLT-KPL0100", supplier_id_id="S1-SSC-1", price=9864865, stock=2),
        PriceList(sku_id_id="SIK-050050-IBB", supplier_id_id="S1-SSC-1", price=189189, stock=72),
        PriceList(sku_id_id="SIK-120120-IBB", supplier_id_id="S1-SSC-1", price=1261261.261, stock=5),
        PriceList(sku_id_id="SIK-040040-IBB", supplier_id_id="S1-SSC-1", price=144144.1441, stock=51),
        PriceList(sku_id_id="SIK-050050-IBB", supplier_id_id="S1-SUM-1", price=189189.1892, stock=72),
    ]

    PriceList.objects.bulk_create(price_lists)


class Migration(migrations.Migration):
    dependencies = [
        ('product', '0003_auto_20230608_1439'),
    ]

    operations = [
        migrations.RunPython(insert_data)
    ]
