# Generated by Django 4.2.1 on 2023-06-07 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fleet',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('capacity', models.IntegerField()),
                ('uom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.unitofmeasure')),
            ],
            options={
                'db_table': 'fleet',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'supplier',
            },
        ),
        migrations.CreateModel(
            name='Logistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=15)),
                ('destination', models.CharField(max_length=15)),
                ('price', models.IntegerField()),
                ('fleet_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.fleet')),
            ],
            options={
                'db_table': 'logistic',
            },
        ),
    ]
