# Generated by Django 4.2.1 on 2023-06-08 07:45

from django.db import migrations


def insert_data(apps, schema_editor):
    Uom = apps.get_model("product", "UnitOfMeasure")
    Fleet = apps.get_model("supplier", "Fleet")
    Logistic = apps.get_model("supplier", "Logistic")

    ton = Uom.objects.get(name='Ton')

    fleets = [
        Fleet(name="Fuso", capacity=8, uom_id=ton),
        Fleet(name="Tronton", capacity=22, uom_id=ton)
    ]

    logistics = [
        Logistic(fleet_type_id="Fuso", origin="Cilincing", destination="Jakarta Timur", price=1600000),
        Logistic(fleet_type_id="Fuso", origin="Cilincing", destination="Jakarta Barat", price=1600000),
        Logistic(fleet_type_id="Fuso", origin="Cilincing", destination="Jakarta Utara", price=1600000),
        Logistic(fleet_type_id="Fuso", origin="Cilincing", destination="Jakarta Selatan", price=1600000),
        Logistic(fleet_type_id="Fuso", origin="Cilincing", destination="Bekasi", price=1800000),
        Logistic(fleet_type_id="Fuso", origin="Cilincing", destination="Depok", price=1800000),
        Logistic(fleet_type_id="Fuso", origin="Cilincing", destination="Cikarang", price=1800000),
        Logistic(fleet_type_id="Fuso", origin="Cilincing", destination="Gunung Sindur", price=1900000),
        Logistic(fleet_type_id="Fuso", origin="Cilincing", destination="Tangerang", price=1800000),
        Logistic(fleet_type_id="Tronton", origin="Cilincing", destination="Jakarta Timur", price=2500000),
        Logistic(fleet_type_id="Tronton", origin="Cilincing", destination="Jakarta Barat", price=2500000),
        Logistic(fleet_type_id="Tronton", origin="Cilincing", destination="Jakarta Utara", price=2500000),
        Logistic(fleet_type_id="Tronton", origin="Cilincing", destination="Jakarta Selatan", price=2500000),
        Logistic(fleet_type_id="Tronton", origin="Cilincing", destination="Bekasi", price=3450000),
        Logistic(fleet_type_id="Tronton", origin="Cilincing", destination="Depok", price=3450000),
        Logistic(fleet_type_id="Tronton", origin="Cilincing", destination="Cikarang", price=3450000),
        Logistic(fleet_type_id="Tronton", origin="Cilincing", destination="Gunung Sindur", price=3600000),
        Logistic(fleet_type_id="Tronton", origin="Cilincing", destination="Tangerang", price=3450000),
    ]

    Fleet.objects.bulk_create(fleets)
    Logistic.objects.bulk_create(logistics)


class Migration(migrations.Migration):
    dependencies = [
        ('supplier', '0002_auto_20230608_1432'),
    ]

    operations = [
        migrations.RunPython(insert_data)
    ]
