# Generated by Django 4.2.1 on 2023-06-08 08:13

from django.db import migrations
from django.utils.datetime_safe import date


def insert_data(apps, schema_editor):
    Uom = apps.get_model("product", "UnitOfMeasure")
    Orders = apps.get_model('orders', 'Orders')
    OrderItems = apps.get_model('orders', 'OrderItems')

    batang = Uom.objects.get(name='Batang')
    lembar = Uom.objects.get(name='Lembar')

    order_1 = Orders(customer_id_id='M1-PUMS-11', order_date=date(2022, 12, 20), status='Accepted')
    order_1.save()
    OrderItems.objects.bulk_create([
        OrderItems(order_id_id=order_1.id, sku_id_id="SIK-040040-IBB", quantity=142, uom_id=batang,
                   unit_selling_price=143694),
        OrderItems(order_id_id=order_1.id, sku_id_id="SIK-060060-IBB", quantity=112, uom_id=batang,
                   unit_selling_price=324775),
        OrderItems(order_id_id=order_1.id, sku_id_id="SIK-070070-IBB", quantity=24, uom_id=batang,
                   unit_selling_price=443243),
        OrderItems(order_id_id=order_1.id, sku_id_id="SIK-080080-IBB", quantity=24, uom_id=batang,
                   unit_selling_price=581982),
        OrderItems(order_id_id=order_1.id, sku_id_id="SIK-090090-KS", quantity=52, uom_id=batang,
                   unit_selling_price=738739),
        OrderItems(order_id_id=order_1.id, sku_id_id="SIK-100100-IBB", quantity=90, uom_id=batang,
                   unit_selling_price=910360),
    ])

    order_2 = Orders(customer_id_id='M1-STQI-11', order_date=date(2023, 1, 17), status='Accepted')
    order_2.save()
    OrderItems.objects.bulk_create([
        OrderItems(order_id_id=order_2.id, sku_id_id="PLT-BRDS0230", quantity=100, uom_id=lembar,
                   unit_selling_price=902832),
        OrderItems(order_id_id=order_2.id, sku_id_id="PLT-SPHC0155", quantity=200, uom_id=lembar,
                   unit_selling_price=502978),
        OrderItems(order_id_id=order_2.id, sku_id_id="PLT-SPHC0180", quantity=50, uom_id=lembar,
                   unit_selling_price=576828),
    ])

    order_3 = Orders(customer_id_id='M1-STQI-11', order_date=date(2023, 1, 19), status='Accepted')
    order_3.save()
    OrderItems.objects.bulk_create([
        OrderItems(order_id_id=order_3.id, sku_id_id="PLT-SPHC0026", quantity=10, uom_id=lembar,
                   unit_selling_price=831644),
        OrderItems(order_id_id=order_3.id, sku_id_id="PLT-SPHC0280", quantity=20, uom_id=lembar,
                   unit_selling_price=902927)
    ])

    order_4 = Orders(customer_id_id='M1-PUMS-11', order_date=date(2023, 1, 20), status='Accepted')
    order_4.save()
    OrderItems.objects.bulk_create([
        OrderItems(
            order_id_id=order_4.id,
            sku_id_id="PIP-SCH404",
            quantity=3,
            uom_id=batang,
            unit_selling_price=1557900
        ),
        OrderItems(
            order_id_id=order_4.id,
            sku_id_id="PIP-SCH4060",
            quantity=3,
            uom_id=batang,
            unit_selling_price=2724300
        ),
        OrderItems(
            order_id_id=order_4.id,
            sku_id_id="PIP-SCH4080",
            quantity=2,
            uom_id=batang,
            unit_selling_price=4158900
        ),
        OrderItems(
            order_id_id=order_4.id,
            sku_id_id="PLT-SPHC0400",
            quantity=3,
            uom_id=lembar,
            unit_selling_price=1782900
        ),
        OrderItems(
            order_id_id=order_4.id,
            sku_id_id="PLT-SPHC0500",
            quantity=5,
            uom_id=lembar,
            unit_selling_price=2364570
        ),
        OrderItems(
            order_id_id=order_4.id,
            sku_id_id="PLT-SPHC0600",
            quantity=4,
            uom_id=lembar,
            unit_selling_price=2946285
        ),
        OrderItems(
            order_id_id=order_4.id,
            sku_id_id="PLT-SPHC1000",
            quantity=1,
            uom_id=lembar,
            unit_selling_price=4766940
        ),
        OrderItems(
            order_id_id=order_4.id,
            sku_id_id="PLT-SPHC1200-GG",
            quantity=11,
            uom_id=lembar,
            unit_selling_price=3540600
        ),
        OrderItems(
            order_id_id=order_4.id,
            sku_id_id="PLT-SPHC1200-GG",
            quantity=14,
            uom_id=lembar,
            unit_selling_price=3540600
        ),
        OrderItems(
            order_id_id=order_4.id,
            sku_id_id="SIK-040040-IBB",
            quantity=51,
            uom_id=batang,
            unit_selling_price=156600
        ),
        OrderItems(
            order_id_id=order_4.id,
            sku_id_id="SIK-050050-IBB",
            quantity=72,
            uom_id=batang,
            unit_selling_price=246600
        ),
        OrderItems(
            order_id_id=order_4.id,
            sku_id_id="SIK-060060-IBB",
            quantity=8,
            uom_id=batang,
            unit_selling_price=353700
        ),
        OrderItems(
            order_id_id=order_4.id,
            sku_id_id="SIK-070070-IBB",
            quantity=8,
            uom_id=batang,
            unit_selling_price=482400
        ),
        OrderItems(
            order_id_id=order_4.id,
            sku_id_id="SIK-080080-IBB",
            quantity=10,
            uom_id=batang,
            unit_selling_price=633150
        ),
        OrderItems(
            order_id_id=order_4.id,
            sku_id_id="SIK-090090-KS",
            quantity=17,
            uom_id=batang,
            unit_selling_price=803700
        ),
        OrderItems(
            order_id_id=order_4.id,
            sku_id_id="SIK-100100-IBB",
            quantity=1,
            uom_id=batang,
            unit_selling_price=990000
        ),
        OrderItems(
            order_id_id=order_4.id,
            sku_id_id="SIK-100100-IBB",
            quantity=18,
            uom_id=batang,
            unit_selling_price=990000
        ),
        OrderItems(
            order_id_id=order_4.id,
            sku_id_id="SIK-120120-IBB",
            quantity=5,
            uom_id=batang,
            unit_selling_price=1446300
        ),
        OrderItems(
            order_id_id=order_4.id,
            sku_id_id="SIK-120120-IBB",
            quantity=20,
            uom_id=batang,
            unit_selling_price=1446300
        )
    ])

    order_5 = Orders(customer_id_id='M1-STQI-11', order_date=date(2023, 1, 20), status='Accepted')
    order_5.save()
    OrderItems.objects.create(
        order_id_id=order_5.id,
        sku_id_id="PLT-SPHC0280",
        quantity=20,
        uom_id=lembar,
        unit_selling_price=902927
    )

    order_6 = Orders(customer_id_id='M1-SUGP-11', order_date=date(2023, 1, 27), status='Accepted')
    order_6.save()
    OrderItems.objects.bulk_create([
        OrderItems(
            order_id_id=order_6.id,
            sku_id_id="SIK-040040-IBB",
            quantity=30,
            uom_id=batang,
            unit_selling_price=162973
        ),
        OrderItems(
            order_id_id=order_6.id,
            sku_id_id="SIK-050050-IBB",
            quantity=60,
            uom_id=batang,
            unit_selling_price=514147
        ),
        OrderItems(
            order_id_id=order_6.id,
            sku_id_id="SIK-060060-IBB",
            quantity=50,
            uom_id=batang,
            unit_selling_price=737809
        ),
        OrderItems(
            order_id_id=order_6.id,
            sku_id_id="SIK-070070-IBB",
            quantity=120,
            uom_id=batang,
            unit_selling_price=503237
        ),
        OrderItems(
            order_id_id=order_6.id,
            sku_id_id="SIK-080080-IBB",
            quantity=15,
            uom_id=batang,
            unit_selling_price=1322680
        ),
        OrderItems(
            order_id_id=order_6.id,
            sku_id_id="SIK-100100-IBB",
            quantity=30,
            uom_id=batang,
            unit_selling_price=1674972
        ),
        OrderItems(
            order_id_id=order_6.id,
            sku_id_id="SIK-120120-IBB",
            quantity=11,
            uom_id=batang,
            unit_selling_price=2542785
        ),
        OrderItems(
            order_id_id=order_6.id,
            sku_id_id="WFL-300-GG",
            quantity=8,
            uom_id=batang,
            unit_selling_price=7706558
        )
    ])

    order_7 = Orders(customer_id_id='M1-ABDI-11', order_date=date(2023, 2, 1), status='Accepted')
    order_7.save()
    OrderItems.objects.create(
        order_id_id=order_7.id,
        sku_id_id="UNP-200",
        quantity=20,
        uom_id=batang,
        unit_selling_price=2162162
    )

    order_8 = Orders(customer_id_id='M1-SURA-11', order_date=date(2023, 2, 2), status='Accepted')
    order_8.save()
    OrderItems.objects.bulk_create([
        OrderItems(
            order_id_id=order_8.id,
            sku_id_id="PLT-SPHC0120",
            quantity=170,
            uom_id=lembar,
            unit_selling_price=432072
        ),
        OrderItems(
            order_id_id=order_8.id,
            sku_id_id="PLT-SPHC0150",
            quantity=20,
            uom_id=lembar,
            unit_selling_price=531261
        ),
        OrderItems(
            order_id_id=order_8.id,
            sku_id_id="PLT-SPHC0200",
            quantity=15,
            uom_id=lembar,
            unit_selling_price=634775
        )
    ])

    order_9 = Orders(customer_id_id='M1-STQI-11', order_date=date(2023, 2, 3), status='Accepted')
    order_9.save()
    OrderItems.objects.create(
        order_id_id=order_9.id,
        sku_id_id="PLT-SPHC0155",
        quantity=50,
        uom_id=lembar,
        unit_selling_price=502978
    )

    order_10 = Orders(customer_id_id='M1-ABDI-11', order_date=date(2023, 2, 6), status='Accepted')
    order_10.save()
    OrderItems.objects.bulk_create([
        OrderItems(
            order_id_id=order_10.id,
            sku_id_id="UNP-120",
            quantity=6,
            uom_id=batang,
            unit_selling_price=1968468.468
        ),
        OrderItems(
            order_id_id=order_10.id,
            sku_id_id="UNP-200",
            quantity=10,
            uom_id=batang,
            unit_selling_price=4533333.333
        )
    ])

    order_11 = Orders(customer_id_id='M1-SUGP-11', order_date=date(2023, 2, 6), status='Accepted')
    order_11.save()

    OrderItems.objects.bulk_create([
        OrderItems(
            order_id_id=order_11.id,
            sku_id_id="PLT-KPL0100",
            quantity=2,
            uom_id=batang,
            unit_selling_price=10333445
        ),
        OrderItems(
            order_id_id=order_11.id,
            sku_id_id="SIK-040040-IBB",
            quantity=100,
            uom_id=batang,
            unit_selling_price=150990
        ),
        OrderItems(
            order_id_id=order_11.id,
            sku_id_id="SIK-050050-IBB",
            quantity=30,
            uom_id=batang,
            unit_selling_price=198175
        ),
        OrderItems(
            order_id_id=order_11.id,
            sku_id_id="SIK-120120-IBB",
            quantity=3,
            uom_id=batang,
            unit_selling_price=1259831
        ),
        OrderItems(
            order_id_id=order_11.id,
            sku_id_id="SIK-120120-IBB",
            quantity=22,
            uom_id=batang,
            unit_selling_price=1321171
        )
    ])

    order_12 = Orders(customer_id_id='M1-SUGP-11', order_date=date(2023, 2, 23), status='Accepted')
    order_12.save()
    OrderItems.objects.bulk_create([
        OrderItems(
            order_id_id=order_12.id,
            sku_id_id="PLT-KPL0100",
            quantity=2,
            uom_id=lembar,
            unit_selling_price=10333445
        ),
        OrderItems(
            order_id_id=order_12.id,
            sku_id_id="SIK-050050-IBB",
            quantity=30,
            uom_id=batang,
            unit_selling_price=198175
        )
    ])

    quotation_1 = Orders(customer_id_id='M1-ABDI-11', status='Pending')
    quotation_1.save()
    OrderItems.objects.bulk_create([
        OrderItems(
            order_id_id=quotation_1.id,
            sku_id_id="UNP-120",
            quantity=10,
            uom_id=batang
        ),
        OrderItems(
            order_id_id=quotation_1.id,
            sku_id_id="UNP-200",
            quantity=6,
            uom_id=batang
        )
    ])

    quotation_2 = Orders(customer_id_id='M1-STQI-11', status='Pending')
    quotation_2.save()
    OrderItems.objects.bulk_create([
        OrderItems(
            order_id_id=quotation_2.id,
            sku_id_id="PLT-BRDS0230",
            quantity=100,
            uom_id=lembar
        ),
        OrderItems(
            order_id_id=quotation_2.id,
            sku_id_id="PLT-SPHC0155",
            quantity=50,
            uom_id=lembar
        ),
        OrderItems(
            order_id_id=quotation_2.id,
            sku_id_id="PLT-SPHC0180",
            quantity=50,
            uom_id=lembar
        )
    ])

    quotation_3 = Orders(customer_id_id='M1-SURA-11', status='Pending')
    quotation_3.save()
    OrderItems.objects.bulk_create([
        OrderItems(
            order_id_id=quotation_3.id,
            sku_id_id="PLT-SPHC0120",
            quantity=170,
            uom_id=lembar
        ),
        OrderItems(
            order_id_id=quotation_3.id,
            sku_id_id="PLT-SPHC0150",
            quantity=20,
            uom_id=lembar
        ),
        OrderItems(
            order_id_id=quotation_3.id,
            sku_id_id="PLT-SPHC0200",
            quantity=15,
            uom_id=lembar
        )
    ])

    quotation_4 = Orders(customer_id_id='M1-PUMS-11', status='Pending')
    quotation_4.save()
    OrderItems.objects.bulk_create([
        OrderItems(
            order_id_id=quotation_4.id,
            sku_id_id="SIK-040040-IBB",
            quantity=51,
            uom_id=batang
        ),
        OrderItems(
            order_id_id=quotation_4.id,
            sku_id_id="SIK-050050-IBB",
            quantity=72,
            uom_id=batang
        ),
        OrderItems(
            order_id_id=quotation_4.id,
            sku_id_id="SIK-060060-IBB",
            quantity=8,
            uom_id=batang
        ),
        OrderItems(
            order_id_id=quotation_4.id,
            sku_id_id="SIK-070070-IBB",
            quantity=8,
            uom_id=batang
        ),
        OrderItems(
            order_id_id=quotation_4.id,
            sku_id_id="SIK-080080-IBB",
            quantity=10,
            uom_id=batang
        ),
        OrderItems(
            order_id_id=quotation_4.id,
            sku_id_id="SIK-120120-IBB",
            quantity=5,
            uom_id=batang
        ),
        OrderItems(
            order_id_id=quotation_4.id,
            sku_id_id="PIP-SCH4080",
            quantity=2,
            uom_id=batang
        )
    ])

    quotation_5 = Orders(customer_id_id='M1-SUGP-11', status='Pending')
    quotation_5.save()
    OrderItems.objects.bulk_create([
        OrderItems(
            order_id_id=quotation_5.id,
            sku_id_id="SIK-100100-IBB",
            quantity=30,
            uom_id=batang
        ),
        OrderItems(
            order_id_id=quotation_5.id,
            sku_id_id="SIK-120120-IBB",
            quantity=11,
            uom_id=batang
        ),
        OrderItems(
            order_id_id=quotation_5.id,
            sku_id_id="SIK-060060-IBB",
            quantity=50,
            uom_id=batang
        ),
        OrderItems(
            order_id_id=quotation_5.id,
            sku_id_id="SIK-070070-IBB",
            quantity=120,
            uom_id=batang
        ),
        OrderItems(
            order_id_id=quotation_5.id,
            sku_id_id="SIK-080080-IBB",
            quantity=15,
            uom_id=batang
        ),
        OrderItems(
            order_id_id=quotation_5.id,
            sku_id_id="WFL-300-GG",
            quantity=8,
            uom_id=batang
        )
    ])


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_data)
    ]
